name: Update Varle Products

on:
  schedule:
    - cron: '0 17 * * *'  # 20:00 Lietuvos laiku (UTC+3 -> 17:00 UTC)
  workflow_dispatch:

jobs:
  update-varle:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests lxml

      # 4. Run update_varle.py
      - name: Run update script
        run: python update_varle.py

      # 5. Commit and push changes
      - name: Commit and push updated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add updated_products.xml stock.csv  # <- jei nenori saugoti zuja._
